name: to_ome_tiff
description: Convert any image format to ome.tiff
keywords:
  - microscopy
  - conversion
modules:
  - bioinfotongli/raw2ometiff
  - bioinfotongli/bioformats2raw
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: |
        List of input FastQ files of size 1 and 2 for single-end and paired-end data,
        respectively.
  - index:
      type: file
      description: Bowtie2 genome index files
      pattern: "*.ebwt"
# TODO Update when we decide on a standard for subworkflow docs
output:
  - bam:
      type: file
      description: Output BAM file containing read alignments
      pattern: "*.{bam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - fastq:
      type: file
      description: Unaligned FastQ files
      pattern: "*.fastq.gz"
  - log:
      type: file
      description: Alignment log
      pattern: "*.log"
authors:
  - "@bioinfotongli"
